version: "3"
services:
    front:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./front
        volumes:
            - /app/node_modules
            - /app/.next
            - ./front:/app
        stdin_open: true

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "38081:80"

    back:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./back
        container_name: app_back
        volumes:
            - ./back:/app
            - /app/node_modules
            - /app/log
